### ISSUE TITLE
ValueError: bad marshall

### ISSUE THREAD

**Issue by gunki22** [htr-tech/Pycompile#2]
I run my script after compile with this pycompiler and got error like this

```
Traceback (most recent call last): File"/storage/emulated/0/proyek/TG/Pycompile/jadi.py", line 6, in <module> (HERE IS ALL ENC SCRIPT)
ValueError: bad marshal data (unknown type code)
```

**Comment by htr-tech** [comment]
@gunki22 this is a py2 encoder only 😩 so encrypt only python2 script..

or you can use the following script to encode your source code
https://github.com/hax0rtahm1d/Encode

**Comment by gunki22** [comment]
Oke thanks,
